//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardStockManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> CustomerCardType { get; set; }
        public string NationalId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string DayOfBirth { get; set; }
        public string PlaceOfBrith { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
    
        public virtual CardType CardType { get; set; }
    }
}
